### ISSUE TITLE
Extend PyEnzyme to include stock solutions

### ISSUE THREAD

**Issue by JR-1991** [EnzymeML/PyEnzyme#53]
PyEnzyme should support managing stock solutions and their respective volumes that are added to individual measurements. Right now PyEnzyme just accepts concentrations that are not related to the species itself, when added to a measurement. However, it is common lab practice to withdraw species from a stock solution and add it to the reaction vessel.

PyEnzyme should be as close as possible to the everyday practice, which could be met by the following proposal:

- Introduce a new Stock solution class, which defines concentration, vendors etc for a species
- Allow users to specify volumes that have been drawn from the stock and added to the reaction vessel
- Use the stock solution's concentration and vessel volume to re-calculate the concentration or amount

**ToDo's***

- [ ] Design ```StockSolution``` class
- [ ] Extend ```Measurement``` class
- [ ] Integrate into the SBML model
